### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gabriel-maxx** [kouzhudong/DllSrv#1]
hello i would like to know if it is possible to use lsass.exe instead of svchost.exe ? i say this because in windows task manager lsass also hosts some services, but svchost is king...

**Comment by kouzhudong** [comment]
谢谢提问。

让lsass.exe加载自己的share dll service，像加载其他服务（SamSs，KeyIso，VaultSvc等）一样，而不是用注入的办法。

这个功能我会考虑的，有时间了尽量实现它（需先深入理解lsass.exe加载共享DLL服务的机制）。

**Comment by kouzhudong** [comment]
另一个思路是编写一个LSA提供者（能获取用户的密码）。

这个DLL需导出：
    NPGetCaps					@1
    NPLogonNotify				@2
    NPPasswordChangeNotify		@3

DLL的注册表的配置如下：
主要的设置是操作注册表,不过这可以编程实现:
1.HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider的order的ProviderOrder后加入一个值,注意逗号.
  HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider的HwOrder的ProviderOrder后可以不加入.
2.HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services下创建刚才键入的值.
3.再在上面(第二步)的路径下创建networkprovider.
4.再在上面(第三步)的路径下创建类型为REG_DWORD的键名Class.
5.再在上面(第三步)的路径下创建类型为REG_MULTI_SZ的键名Name.
6.再在上面(第三步)的路径下创建类型为REG_MULTI_SZ的键名ProviderPath.
7.可以没有:HKEY_LOCAL_MACHINE,"SYSTEM\\CurrentControlSet\\Control\\Lsa"的Notification Packages后添加一个值.
8.HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Notifyees这个没有实验.

made by correy
made at 2014.03.06
email:kouleguan at hotmail dot com
homepage:http://correy.webs.com

Windows-classic-samples\Samples\Win7Samples\security里有相关的内容。

**Comment by gabriel-maxx** [comment]
@kouzhudong thanks for replying if you can add an example soon like you did with svchost i will be grateful

**Comment by kouzhudong** [comment]
you can use google to find my blog:
https://leguanyuan.blogspot.com/2014/03/windows.html
This is a complete example code.

**Comment by gabriel-maxx** [comment]
> you can use google to find my blog: https://leguanyuan.blogspot.com/2014/03/windows.html This is a complete example code.

Could you upload a visual studio project please? like you did with svchost..

**Comment by kouzhudong** [comment]
以后有时间了弄个仓库，但是时间不确定。

**Comment by gabriel-maxx** [comment]
> 以后有时间了弄个仓库，但是时间不确定。

thanks for considering

**Comment by kouzhudong** [comment]
https://github.com/kouzhudong/LogonNP.git

**Comment by gabriel-maxx** [comment]
> https://github.com/kouzhudong/LogonNP.git

thank you friend
